# .github/workflows/docker-build.yml
name: Frontend deploy kubernetes

inputs:
  container-access-token:
    description: 'El token para loguearse'
    required: true
  type:
    description: 'El tipo de despliegue (carpeta dentro de helm-template)'
    required: true


runs:
  using: "composite"
  steps:
      - name: Checkout helm repository
        uses: actions/checkout@v4
        with:
          repository: codeparceorg/helm-template
          token: ${{ github.token }}
          path: helm-template
          
      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace $NS --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ inputs.container-access-token }} \
          --namespace=$NS \
          --dry-run=client -o yaml | kubectl apply -f -

          echo "Secret created."

          mv env.template helm-template/${{ inputs.type }}/.env && cd helm-template/${{ inputs.type }}
          
          export IMAGE_TAG=${GITHUB_SHA::7}

          envsubst < values.template > values.yaml
          echo "Map values.yaml created."

          helm upgrade --install ${GITHUB_REPOSITORY_NAME} . --namespace $NS --create-namespace --wait=false
          echo "Deploying ${GITHUB_REPOSITORY_NAME} with Helm "
        shell: bash

