name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      cloud:
        type: string


jobs:
  build:
    uses: ./.github/workflows/ci.build.node.yml
    with:
      type: service-build
      target: dist
      doppler-project: vault-codeparce
    secrets: inherit
    
  publish:
    needs: build
    uses: ./.github/workflows/ci.docker.yml
    with:
      type: service-build
      target: dist
    secrets: inherit

  infra:
    needs: publish
    uses: ./.github/workflows/infra.tf.yml
    with:
      tf-directory: 5-container-app
      cloud: ${{ inputs.cloud }}
    secrets: inherit