# .github/workflows/docker-build.yml
name: Clear the Imagens

inputs:
  package-name:
    description: 'Nombre del paackage a limpiar'
    required: true
  github-token:
    description: 'Token del runner de github'
    required: true

runs:
  using: composite

  steps:
    - name: Test GitHub API
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/orgs/codeparceorg/packages/container/${{inputs.package-name}}

    - uses: actions/delete-package-versions@v5
      with:
        owner: codeparceorg
        package-name: ${{inputs.package-name}}
        package-type: container
        min-versions-to-keep: 2
        delete-only-untagged-versions: false
        token: ${{ inputs.github-token }}